export const LANG_TH_TRANS = {
    'login': 'เข้าสู่ระบบ',
    'email': 'อีเมล',
    'password': 'รหัสผ่าน',
    
    'products': 'สินค้า',
    'orders': 'รายการสั่งซื้อ',
    'shipping_list': 'ใบนำส่ง',
    'settings': 'การตั้งค่า',
    'shop_info': 'ข้อมูลร้านค้า',
    'address': 'ที่อยู่',
    'address_book': 'สมุดที่อยู่',
    'logout': 'ออกจากระบบ',
    
    'edit': 'แก้ไข',
    'delete': 'ลบ',
    'save': 'บันทึก',
    'submit': 'ทำรายการ',
    'cancel': 'ยกเลิก',
    'select_all': 'เลือกทั้งหมด',
    'action': 'คำสั่ง',
    'create_label': 'ทำจ่าหน้า',
    'add_tracking': 'ใส่หมายเลขสิ่งของ',
    'mark_as_shipped': 'ยืนยันการจัดส่ง',
    'add_new_product': 'เพิ่มสินค้าใหม่',
    'edit_product': 'แก้ไขสินค้า',
    'print_multi_label': 'พิมพ์หลายจ่าหน้า',
    'add_new_address': 'เพิ่มที่อยู่ใหม่',
    'create_stock_item': 'ทำใบจัดสินค้า',
    'print_label': 'พิมพ์จ่าหน้า',
    
    'product_name': 'ชื่อสินค้า',
    'category': 'ประเภท',
    'price': 'ราคา',
    'quantity': 'จำนวน',
    'description': 'รายละเอียด',
    'sender_info': 'ข้อมูลผู้ส่ง',
    'delivery_info': 'ข้อมูลผู้รับ',
    'service_type': 'ประเภทบริการ',
    'order_no': 'เลขที่คำสั่งซื้อ',
    'date': 'วันที่',
    'payment_option': 'วิธีชำระเงิน',
    'name': 'ชื่อ',
    'province': 'จังหวัด',
    'district': 'อำเภอ',
    'postcode': 'รหัสไปรษณีย์',
    'telephone': 'โทรศัพท์',
    'set_as_default': 'ตั้งเป็นค่าเริ่มต้น',   
    'weight': 'น้ำหนัก',   
    'kg': 'กิโลกรัม',   
    'tracking_no': 'หมายเลขสิ่งของ',
    'total_qty': 'จำนวนรวม',
    'units': 'ชิ้น'
};